In [19]:
import pandas as pd
from conexao_oracle import conexao_local_host

dados = pd.read_csv('tbl_cep_201805_csv.csv',encoding="ISO-8859-1")

In [ ]:
dados

In [20]:
dados_filtrados   = dados[['estado','bairro','cidade','cep','latitude','longitude']]
bairros_filtrados = dados_filtrados.dropna(subset=['cidade','bairro','cep'])
bairros = bairros_filtrados.drop_duplicates(subset='cep')

In [21]:
bairros

,estado,bairro,cidade,cep,latitude,longitude
0,SP,Sé,São Paulo,1001000,-23.550278,-46.634218
1,SP,Sé,São Paulo,1001001,-23.549865,-46.634020
2,SP,Sé,São Paulo,1001010,-23.551479,-46.633272
3,SP,Sé,São Paulo,1001900,-23.549896,-46.634378
4,SP,Sé,São Paulo,1001901,-23.551829,-46.634234
...,...,...,...,...,...,...
1108496,RS,Centro,Ciríaco,99970970,-28.343090,-51.871852
1108498,RS,Centro,São João Bosco (Ciríaco),99975970,-30.301702,-51.323903
1108501,RS,Centro,David Canabarro,99980970,-28.387671,-51.846788
1108502,RS,Capela São José do Capingui (Distrito),David Canabarro,99980974,-28.451355,-51.880714
1108504,RS,Centro,Muliterno,99990971,-29.271065,-51.987159

In [ ]:

conexao = conexao_local_host()
with conexao.cursor() as cursor:
    l = 0
    for index,linha in bairros.iterrows():
        cursor.callproc('SP_INSERIR_BAIRRO',[linha[0],linha[1],linha[2],linha[3],linha[4],linha[5]])
        if index % 1000 == 0:
            conexao.commit()